-- =====================================================================
-- 0014 -- D5A: MarketObservation substrate (PROPOSED, NOT APPLIED to data1_dev)
-- =====================================================================
-- STATUS: proposed by this dispatch, NOT yet run against any database.
-- Per the standing "never modify historical migrations" rule, this is a
-- NEW additive file -- 0001 through 0013 are untouched. Applying this
-- migration to live data1_dev requires explicit authorization (a future
-- D5A live-apply dispatch, not this pass).
--
-- CONTRACT (GrailKey Physical Asset Protocol v1, Foundation Law 5 --
-- "Market = observations -> applicability -> population -> valuation"):
-- market_observation is a durable statement of what an external market
-- source reported, or what GrailKey directly observed. It is evidence,
-- never valuation truth. This migration implements ONLY this one table
-- -- no Applicability, no MarketPopulation, no wiring to comp_snapshot
-- or valuation_event. Those are later D5 phases (D5B/D5C), deliberately
-- not built here, per the ratified sequencing (D5A dispatch, 2026-09-03,
-- A4): D5A substrate -> D5B Applicability -> D5C MarketPopulation +
-- D3.3 bridge -> D5D controlled provider capture. No direct
-- MarketObservation -> ValuationEvent shortcut is permitted at any phase.
--
-- A1 (D5A dispatch, 2026-09-03) -- NO asset_id column, deliberately, and
-- NOT merely nullable. Contrast directly with asset_raw_observation
-- (0013:197-199, `asset_id UUID NOT NULL REFERENCES gk_asset(id)`) --
-- that binding is genuinely intrinsic (raw evidence physically gathered
-- FROM the asset in hand: a barcode scan, a vision-OCR read). A market
-- observation carries no such physical binding -- it is generated by a
-- third party, independently of whether GrailKey ever queries it, and
-- its relevance to zero, one, or many gkAssetIds is a JUDGMENT
-- (Applicability, D5B), never a fact the observation itself carries.
-- Writing asset_id here, even nullable, would create a standing
-- temptation to skip Applicability and stamp an asset relationship
-- directly at observation-creation time -- removing the column makes
-- that architecturally impossible, not merely discouraged.
--
-- A2/S1-S3 (D5A dispatch + D5A semantic closure, 2026-09-03) --
-- content_hash follows its OWN canonical contract (mo-hash-v1,
-- src/lib/marketObservationHash.js), deliberately diverging from
-- comp_snapshot.content_hash's reused-but-fragile plain-JSON.stringify
-- approach (verified not actually canonical -- caller object key order,
-- unversioned). mo-hash-v1's tuple is: version tag, provider,
-- provider_item_id, listing_kind, price_amount, currency,
-- condition_text, grade_numeric, occurred_at -- observed_at/recorded_at/
-- id/recorded_by_principal_id/correlation_id/raw_payload/content_hash
-- itself NEVER participate (provenance/timing metadata, not observed
-- market fact). occurred_at's inclusion is a deliberate, load-bearing
-- correction (S1): two distinct real market events (e.g. two
-- PriceCharting sales at the identical price on different dates) must
-- never silently collapse into one row via dedup.
--
-- A2a -- provider_item_id stays plain nullable TEXT, no reserved
-- sentinel (deliberately diverges from D4 Ruling 13's issuing_authority
-- UNKNOWN-sentinel pattern -- the two identity models differ: D4's NULL
-- hazard was FALSE-MERGING two different real identifiers; a NULL
-- provider_item_id here only makes the dedup scope inert for that row
-- (every such observation independently new), never a false merge).
--
-- S2 -- price_amount is canonical decimal NUMERIC(14,4), never integer
-- minor-units -- the kernel must not need per-currency exponent
-- knowledge (JPY=0, USD=2, BHD=3, ...) merely to preserve an observed
-- price. Source-specific cents/decimal representations are normalized
-- at the adapter boundary (not built here), never encoded into this
-- schema.
--
-- D2a -- grade_numeric is NUMERIC(3,1), matching the existing
-- valuation_event.grade_assumption precedent (0004:185) and the
-- CGC/CBCS one-decimal grading convention exactly.
--
-- A3 -- raw_payload is nullable and rights-gated at the SERVICE/adapter
-- call layer (not built here), never by a schema column -- this table
-- stays rights-agnostic and provider-neutral by design. No eBay/
-- PriceCharting production persistence, raw or derived, is authorized
-- until GK-182 (evidenceContracts.js's own retention-day documentation
-- inconsistency) is resolved and the corresponding source policy
-- explicitly grants it.
--
-- A4a -- correlation_id supports the ratified batch write-ceremony (one
-- retrieval batch = one transaction = one domain_event/outbox pair, not
-- one per observation row) -- every row in one batch shares the same
-- correlation_id as its one domain_event, so individual observation
-- provenance stays fully recoverable even though the event/idempotency
-- ceremony itself is batched, not per-row. The domain_event/outbox
-- writer and the batch service function are not built here (this
-- migration is schema only).
--
-- IMMUTABILITY -- DB-enforced via trigger, matching comp_snapshot
-- (0012)/asset_raw_observation (0013)'s own precedent exactly: once a
-- row exists, UPDATE and DELETE both raise a real exception. A provider
-- correction or a changed market fact creates a NEW row; it never
-- mutates an existing one.
--
-- D3.3 RELATIONSHIP -- UNDER (ratified, D5A Phase 0). This migration
-- touches NEITHER comp_snapshot NOR valuation_event -- zero columns
-- added, zero rows touched, zero backfill, zero decomposition of
-- existing snapshots into synthetic observation rows. Pre-D5 comp_
-- snapshot rows remain permanently opaque historical evidence.
--
-- REVERSIBILITY -- every statement below is reversible without any risk
-- to existing data: market_observation does not exist yet (DROP
-- TRIGGER / DROP FUNCTION / DROP TABLE undoes it completely), and no
-- existing table (0001-0013) is touched at all -- this migration adds
-- exactly one new, wholly self-contained table. The rollback,
-- db/data0/0014_d5a_market_observation_rollback.sql, removes exactly
-- what this file adds, in FK-safe dependency order, and nothing else.
-- =====================================================================

SET search_path TO data1_dev;

CREATE TABLE market_observation (
  id                        UUID PRIMARY KEY,

  -- Provenance: generic string, not an enum -- matches comp_snapshot.
  -- source's own convention. Examples: 'ebay-browse-api',
  -- 'pricecharting-scrape', 'manual'. No comic-specific value implied.
  provider                  TEXT NOT NULL,

  -- Cross-time correlation to the same external object -- deliberately
  -- PLAIN and non-unique (A2a). NULL is legal (an ID-less source, e.g.
  -- a bare price-ladder row with no discrete item ID) and never
  -- fabricated to satisfy a uniqueness requirement that doesn't exist.
  provider_item_id          TEXT,

  -- Generic vocabulary, plain CHECK (not a DB enum type) -- matches
  -- valuation_event.method's own convention (0004:183).
  listing_kind              TEXT NOT NULL CHECK (listing_kind IN ('asking', 'sold', 'offer', 'auction-result')),

  -- S2 -- canonical decimal, ISO 4217 currency, both independently
  -- nullable. A price observed with unknown currency, or a currency
  -- known with unknown price, are both legal, distinct states -- never
  -- collapsed or defaulted.
  price_amount              NUMERIC(14, 4) CHECK (price_amount IS NULL OR price_amount >= 0),
  currency                  TEXT,

  condition_text            TEXT,
  -- D2a -- one-decimal grading convention, matches valuation_event.
  -- grade_assumption (0004:185) exactly.
  grade_numeric              NUMERIC(3, 1),

  -- Three-axis time (G7/S1, ratified): occurred_at is the asserted
  -- real-world market-event time -- nullable, never inferred, never
  -- defaulted from observed_at or recorded_at. observed_at is when
  -- GrailKey/the provider's retrieval actually fetched this evidence --
  -- always known (the retrieval itself happened), NOT NULL. recorded_at
  -- is GrailKey's own persistence time -- always known, NOT NULL
  -- DEFAULT now(). No CHECK constraint relates any of the three to each
  -- other -- backdated/future-dated/out-of-order values are all
  -- structurally legal, matching Law 3's already-ratified precedent
  -- (db/data0/0011_d3_2_event_time.sql).
  occurred_at                TIMESTAMPTZ,
  observed_at                TIMESTAMPTZ NOT NULL,
  recorded_at                TIMESTAMPTZ NOT NULL DEFAULT now(),

  recorded_by_principal_id  UUID NOT NULL REFERENCES gk_principal(id),

  -- A4a -- shared by every row in one retrieval batch; the batch's one
  -- domain_event carries the same value, so a normal SELECT WHERE
  -- correlation_id = X reconstructs the full batch on demand, even
  -- though the event/idempotency ceremony itself is batched.
  correlation_id            UUID NOT NULL,

  -- A2/S1-S3 -- mo-hash-v1 (src/lib/marketObservationHash.js). The
  -- version tag is embedded IN the hash input itself (S3) -- this
  -- column additionally stores it in queryable form, so a future
  -- v1-vs-v2 audit never has to reverse an opaque hash to know which
  -- contract produced it.
  content_hash              TEXT NOT NULL,
  hash_contract_version      TEXT NOT NULL DEFAULT 'mo-hash-v1',

  -- A3 -- nullable, rights-gated at the service/adapter layer (never a
  -- schema-level rights check -- that would contaminate a permanent-
  -- domain table with provider-policy concerns). Excluded from the
  -- content hash (raw formatting noise must never defeat dedup of a
  -- genuinely unchanged fact).
  raw_payload                JSONB
);

-- A2a -- plain UNIQUE index, ordinary Postgres NULL-is-distinct
-- semantics (deliberately NOT "NULLS NOT DISTINCT"): inert whenever
-- provider_item_id IS NULL, by design -- an ID-less observation is
-- always treated as independently new, never falsely merged with
-- another ID-less observation that happens to share provider+hash.
CREATE UNIQUE INDEX market_observation_dedup_key ON market_observation (provider, provider_item_id, content_hash);

-- A4a -- batch-recovery lookup.
CREATE INDEX ON market_observation (correlation_id);

-- Ordinary cross-time correlation lookup (A2a) -- distinct from the
-- dedup unique index above, useful even when content_hash differs
-- (i.e. "show me every observation of this listing, changed or not").
CREATE INDEX ON market_observation (provider, provider_item_id);

CREATE OR REPLACE FUNCTION market_observation_immutable() RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'market_observation rows are immutable once written -- % on market_observation.id=% is not permitted (a provider correction or a changed market fact creates a NEW row; it never mutates an existing one)', TG_OP, OLD.id;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER market_observation_no_update BEFORE UPDATE ON market_observation FOR EACH ROW EXECUTE FUNCTION market_observation_immutable();
CREATE TRIGGER market_observation_no_delete BEFORE DELETE ON market_observation FOR EACH ROW EXECUTE FUNCTION market_observation_immutable();
