-- =====================================================================
-- 0014 -- D5A: MarketObservation substrate (PROPOSED, NOT APPLIED to data1_dev)
-- =====================================================================
-- STATUS: proposed by this dispatch, NOT yet run against any database.
-- Per the standing "never modify historical migrations" rule, this is a
-- NEW additive file -- 0001 through 0013 are untouched. Applying this
-- migration to live data1_dev requires explicit authorization (a future
-- D5A live-apply dispatch, not this pass).
--
-- CONTRACT (GrailKey Physical Asset Protocol v1, Foundation Law 5 --
-- "Market = observations -> applicability -> population -> valuation"):
-- market_observation is a durable statement of what an external market
-- source reported, or what GrailKey directly observed. It is evidence,
-- never valuation truth. This migration implements ONLY this one table
-- -- no Applicability, no MarketPopulation, no wiring to comp_snapshot
-- or valuation_event. Those are later D5 phases (D5B/D5C), deliberately
-- not built here, per the ratified sequencing (D5A dispatch, 2026-09-03,
-- A4): D5A substrate -> D5B Applicability -> D5C MarketPopulation +
-- D3.3 bridge -> D5D controlled provider capture. No direct
-- MarketObservation -> ValuationEvent shortcut is permitted at any phase.
--
-- A1 (D5A dispatch, 2026-09-03) -- NO asset_id column, deliberately, and
-- NOT merely nullable. Contrast directly with asset_raw_observation
-- (0013:197-199, `asset_id UUID NOT NULL REFERENCES gk_asset(id)`) --
-- that binding is genuinely intrinsic (raw evidence physically gathered
-- FROM the asset in hand: a barcode scan, a vision-OCR read). A market
-- observation carries no such physical binding -- it is generated by a
-- third party, independently of whether GrailKey ever queries it, and
-- its relevance to zero, one, or many gkAssetIds is a JUDGMENT
-- (Applicability, D5B), never a fact the observation itself carries.
--
-- A2/S1-S3/F1-F2 (D5A dispatch, D5A semantic closure, and this FINAL
-- PRE-LIVE REPRESENTATION CLOSURE, all 2026-09-03) -- content_hash
-- follows its OWN canonical contract (mo-hash-v1, src/lib/
-- marketObservationHash.js), deliberately diverging from comp_snapshot.
-- content_hash's reused-but-fragile plain-JSON.stringify approach
-- (verified not actually canonical -- caller object key order,
-- unversioned). mo-hash-v1's final tuple is: version tag, provider,
-- provider_item_id, listing_kind, price_amount, currency,
-- condition_text, grade_numeric, grade_basis, occurred_on, occurred_at
-- -- observed_at/recorded_at/id/recorded_by_principal_id/correlation_id/
-- raw_payload/content_hash itself NEVER participate (provenance/timing
-- metadata, not observed market fact).
--
-- A2a -- provider_item_id stays plain nullable TEXT, no reserved
-- sentinel (deliberately diverges from D4 Ruling 13's issuing_authority
-- UNKNOWN-sentinel pattern -- the two identity models differ: D4's NULL
-- hazard was FALSE-MERGING two different real identifiers; a NULL
-- provider_item_id here only makes the dedup scope inert for that row
-- (every such observation independently new), never a false merge).
--
-- S2 -- price_amount is canonical decimal NUMERIC(14,4), never integer
-- minor-units -- the kernel must not need per-currency exponent
-- knowledge (JPY=0, USD=2, BHD=3, ...) merely to preserve an observed
-- price. Source-specific cents/decimal representations are normalized
-- at the adapter boundary (not built here), never encoded into this
-- schema.
--
-- F1/F1b (FINAL PRE-LIVE REPRESENTATION CLOSURE, 2026-09-03 -- supersedes
-- the intermediate T1/T1a occurred_at_precision draft entirely) -- a
-- prior draft fixed HASH semantics for date-only facts but still
-- physically STORED a manufactured midnight instant
-- ("2026-06-14T00:00:00.000Z") for a source that asserted only a
-- calendar date, with a separate qualifier column saying so. That is
-- insufficient: a schema must prevent the accidental interpretation of
-- a synthetic midnight as a real event time, not merely annotate it
-- after the fact. Temporal representation is now fully structural:
-- TWO independent nullable columns, occurred_on (DATE) and occurred_at
-- (TIMESTAMPTZ). Presence alone is the discriminator -- both NULL =
-- event time unknown; occurred_on populated alone = a DATE fact (the
-- source asserted a calendar date only, no time-of-day, and the
-- canonical value is the bare date itself -- NO instant, synthetic or
-- otherwise, is ever constructed or stored for this case); occurred_at
-- populated alone = an INSTANT fact (the source asserted a specific
-- point in time). Both populated is REJECTED by the CHECK below --
-- exactly one asserted-fact representation, or neither, never both.
-- occurred_at_precision (the prior draft's qualifier column) is REMOVED
-- entirely -- under this two-column model it would be a second,
-- independently-mutable source of truth for information already fully
-- determined by column presence; no additional semantic survives its
-- removal that cannot be derived from which of the two columns is
-- non-null.
--
-- F1a -- observed_at means EXACTLY ONE THING: the timestamp of the
-- actual upstream provider retrieval that produced the payload/facts
-- being persisted. It must NEVER mean cache-read time, persistence
-- time, request-handling time, or enrichment-completion time.
-- PriceCharting's own HTML scrape is cached up to 7 days
-- (api/kv-cache.js:147, KV_TTL.PC_HTML=604800) -- if a future writer
-- stamped observed_at=now() at PERSISTENCE time on a cache-hit path, it
-- would manufacture up to 7 days of false freshness. This is not yet a
-- live hazard (confirmed: api/kv-cache.js's kvGet/kvSet store and
-- return only the raw cached value today, api/kv-cache.js:60-90 -- no
-- fetch-timestamp metadata travels with a cached entry at all, so
-- nothing currently claims to solve this). Logged as **GK-184**: before
-- any rights-gated production capture (D5D) is enabled, the provider
-- retrieval timestamp must be threaded through the cache layer itself
-- (stored alongside the cached payload, returned on every cache hit)
-- so that observed_at is always sourced from the ORIGINAL fetch, never
-- fabricated at persistence time. No cache/adapter wiring is built by
-- this migration -- schema only. recorded_at remains GrailKey's own
-- persistence time, independent of observed_at exactly as before.
--
-- F1c -- both occurred_on and occurred_at participate in mo-hash-v1 as
-- two independent fields (src/lib/marketObservationHash.js). This makes
-- "DATE fact" and "genuinely-midnight-UTC INSTANT fact for the same
-- calendar date" automatically byte-distinct -- they populate different
-- columns entirely, so no synthetic marker is needed to tell them apart
-- the way occurred_at_precision previously had to.
--
-- F1d -- deliberate asymmetry, recorded explicitly: D3.2's occurred_at
-- on the seven asset-kernel event tables (db/data0/0011) carries no
-- partial-precision representation, and this is intentional, not an
-- oversight to retrofit. Those are operator/system-asserted events,
-- generated within GrailKey's own event semantics -- there is no
-- partial-precision third-party report to preserve. MarketObservation's
-- temporal fields are fundamentally different: third-party-reported
-- evidence that may arrive as only a partial temporal fact. Do not
-- retrofit occurred_on onto 0011's seven tables merely for consistency.
--
-- T2/T2a (unchanged by this closure) -- grade_numeric is NUMERIC(12,6),
-- NOT a comic-specific fixed one-decimal scale. The bound is chosen
-- purely for generic database/domain safety, naming no grading
-- convention. Canonicalization (canonicalMinimalDecimal, src/lib/
-- marketObservationHash.js) strips only insignificant trailing
-- fractional zeros -- no fixed-scale padding, unlike price_amount
-- above (money has a real, currency-defined natural precision; a
-- numeric grade/condition-index does not have one universal natural
-- precision across verticals).
--
-- F2/F2a/F2b (FINAL PRE-LIVE REPRESENTATION CLOSURE, 2026-09-03 --
-- closes the T2b-disclosed gap directly rather than deferring it) --
-- grade_basis added: a nullable, generic, source-asserted qualifier
-- (e.g. whatever string a provider's own page/API names its scale as).
-- Never invented, inferred, or defaulted by GrailKey; no hardcoded
-- CGC/CBCS vocabulary anywhere in this schema. Participates in
-- mo-hash-v1. F2a: a grade with NO asserted basis (grade_basis IS NULL)
-- is a genuinely different, distinct fact from the identical numeric
-- grade WITH an asserted basis -- presence-tagged hash serialization
-- makes this automatic, proven live (see the migration-contract test).
-- Two observations from the same provider with an identical
-- grade_numeric, both with grade_basis IS NULL, and otherwise identical
-- facts, MAY legitimately deduplicate -- that is the correct behavior,
-- not a defect: GrailKey preserves exactly the absence the provider
-- itself asserted, rather than inventing a distinction the source never
-- made.
--
-- F2 (residual, disclosed, not silently accepted as fully closed) --
-- grade_basis being NULLABLE is semantically correct (F2a), but it
-- means a single provider that reports on two genuinely different
-- numeric sub-scales of its OWN, without ever disclosing which, is
-- still not protected by schema alone (the DEDUP-across-providers
-- hazard T2b originally named IS now closed: provider already
-- participates in the unique index and hash tuple, proven live).
-- Logged as **GK-183** (narrowed from T2b's original, now-resolved
-- finding): the residual is specifically single-provider,
-- multi-sub-scale, NULL-basis ambiguity, not the original
-- zero-qualifier gap.
--
-- A3 -- raw_payload is nullable and rights-gated at the SERVICE/adapter
-- call layer (not built here), never by a schema column -- this table
-- stays rights-agnostic and provider-neutral by design. No eBay/
-- PriceCharting production persistence, raw or derived, is authorized
-- until GK-182 (evidenceContracts.js's own retention-day documentation
-- inconsistency) is resolved and the corresponding source policy
-- explicitly grants it.
--
-- A4a -- correlation_id supports the ratified batch write-ceremony (one
-- retrieval batch = one transaction = one domain_event/outbox pair, not
-- one per observation row) -- every row in one batch shares the same
-- correlation_id as its one domain_event, so individual observation
-- provenance stays fully recoverable even though the event/idempotency
-- ceremony itself is batched, not per-row. The domain_event/outbox
-- writer and the batch service function are not built here (this
-- migration is schema only).
--
-- IMMUTABILITY -- DB-enforced via trigger, matching comp_snapshot
-- (0012)/asset_raw_observation (0013)'s own precedent exactly: once a
-- row exists, UPDATE and DELETE both raise a real exception. A provider
-- correction or a changed market fact creates a NEW row; it never
-- mutates an existing one.
--
-- D3.3 RELATIONSHIP -- UNDER (ratified, D5A Phase 0). This migration
-- touches NEITHER comp_snapshot NOR valuation_event -- zero columns
-- added, zero rows touched, zero backfill, zero decomposition of
-- existing snapshots into synthetic observation rows. Pre-D5 comp_
-- snapshot rows remain permanently opaque historical evidence.
--
-- REVERSIBILITY -- every statement below is reversible without any risk
-- to existing data: market_observation does not exist yet (DROP
-- TRIGGER / DROP FUNCTION / DROP TABLE undoes it completely), and no
-- existing table (0001-0013) is touched at all -- this migration adds
-- exactly one new, wholly self-contained table. The rollback,
-- db/data0/0014_d5a_market_observation_rollback.sql, removes exactly
-- what this file adds, in FK-safe dependency order, and nothing else.
-- =====================================================================

SET search_path TO data1_dev;

CREATE TABLE market_observation (
  id                        UUID PRIMARY KEY,

  -- Provenance: generic string, not an enum -- matches comp_snapshot.
  -- source's own convention. Examples: 'ebay-browse-api',
  -- 'pricecharting-scrape', 'manual'. No comic-specific value implied.
  provider                  TEXT NOT NULL,

  -- Cross-time correlation to the same external object -- deliberately
  -- PLAIN and non-unique (A2a). NULL is legal (an ID-less source, e.g.
  -- a bare price-ladder row with no discrete item ID) and never
  -- fabricated to satisfy a uniqueness requirement that doesn't exist.
  provider_item_id          TEXT,

  -- Generic vocabulary, plain CHECK (not a DB enum type) -- matches
  -- valuation_event.method's own convention (0004:183).
  listing_kind              TEXT NOT NULL CHECK (listing_kind IN ('asking', 'sold', 'offer', 'auction-result')),

  -- S2 -- canonical decimal, ISO 4217 currency, both independently
  -- nullable. A price observed with unknown currency, or a currency
  -- known with unknown price, are both legal, distinct states -- never
  -- collapsed or defaulted.
  price_amount              NUMERIC(14, 4) CHECK (price_amount IS NULL OR price_amount >= 0),
  currency                  TEXT,

  condition_text            TEXT,
  -- T2/T2a -- generic numeric bound, no grading-convention-specific
  -- scale (see the header). Canonicalized via canonicalMinimalDecimal,
  -- never a fixed-scale pad.
  grade_numeric              NUMERIC(12, 6),
  -- F2/F2a/F2b -- nullable, generic, source-asserted qualifier for
  -- grade_numeric. NULL means the source asserted no basis -- preserved
  -- exactly, never invented (see the header for the full rule).
  grade_basis                TEXT,

  -- F1/F1a/F1b/F1c -- structural temporal representation. Exactly one
  -- of occurred_on/occurred_at may be populated (or neither); the CHECK
  -- below rejects both-populated. NO synthetic instant is ever
  -- manufactured for a date-only fact -- occurred_on's canonical value
  -- is the bare calendar date itself. observed_at is the actual
  -- upstream PROVIDER RETRIEVAL time (see the header, F1a) -- never
  -- cache-read/persistence/request-handling/enrichment-completion time
  -- -- always known (a retrieval genuinely happened), NOT NULL.
  -- recorded_at is GrailKey's own persistence time -- always known,
  -- NOT NULL DEFAULT now(), independent of observed_at. No CHECK
  -- constraint relates occurred_on/occurred_at to observed_at/
  -- recorded_at -- backdated/future-dated/out-of-order values are all
  -- structurally legal, matching Law 3's already-ratified precedent
  -- (db/data0/0011_d3_2_event_time.sql).
  occurred_on                DATE,
  occurred_at                TIMESTAMPTZ,
  CHECK (occurred_on IS NULL OR occurred_at IS NULL),
  observed_at                TIMESTAMPTZ NOT NULL,
  recorded_at                TIMESTAMPTZ NOT NULL DEFAULT now(),

  recorded_by_principal_id  UUID NOT NULL REFERENCES gk_principal(id),

  -- A4a -- shared by every row in one retrieval batch; the batch's one
  -- domain_event carries the same value, so a normal SELECT WHERE
  -- correlation_id = X reconstructs the full batch on demand, even
  -- though the event/idempotency ceremony itself is batched.
  correlation_id            UUID NOT NULL,

  -- A2/S1-S3/F1-F2 -- mo-hash-v1 (src/lib/marketObservationHash.js). The
  -- version tag is embedded IN the hash input itself (S3) -- this
  -- column additionally stores it in queryable form, so a future
  -- v1-vs-v2 audit never has to reverse an opaque hash to know which
  -- contract produced it.
  content_hash              TEXT NOT NULL,
  hash_contract_version      TEXT NOT NULL DEFAULT 'mo-hash-v1',

  -- A3 -- nullable, rights-gated at the service/adapter layer (never a
  -- schema-level rights check -- that would contaminate a permanent-
  -- domain table with provider-policy concerns). Excluded from the
  -- content hash (raw formatting noise must never defeat dedup of a
  -- genuinely unchanged fact).
  raw_payload                JSONB
);

-- A2a -- plain UNIQUE index, ordinary Postgres NULL-is-distinct
-- semantics (deliberately NOT "NULLS NOT DISTINCT"): inert whenever
-- provider_item_id IS NULL, by design -- an ID-less observation is
-- always treated as independently new, never falsely merged with
-- another ID-less observation that happens to share provider+hash.
CREATE UNIQUE INDEX market_observation_dedup_key ON market_observation (provider, provider_item_id, content_hash);

-- A4a -- batch-recovery lookup.
CREATE INDEX ON market_observation (correlation_id);

-- Ordinary cross-time correlation lookup (A2a) -- distinct from the
-- dedup unique index above, useful even when content_hash differs
-- (i.e. "show me every observation of this listing, changed or not").
CREATE INDEX ON market_observation (provider, provider_item_id);

CREATE OR REPLACE FUNCTION market_observation_immutable() RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'market_observation rows are immutable once written -- % on market_observation.id=% is not permitted (a provider correction or a changed market fact creates a NEW row; it never mutates an existing one)', TG_OP, OLD.id;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER market_observation_no_update BEFORE UPDATE ON market_observation FOR EACH ROW EXECUTE FUNCTION market_observation_immutable();
CREATE TRIGGER market_observation_no_delete BEFORE DELETE ON market_observation FOR EACH ROW EXECUTE FUNCTION market_observation_immutable();
